### ISSUE TITLE
リセットCSSを使用するか否か

### ISSUE THREAD

**Issue by sejsokdjfpsakd** [MutsumeWebDev/training1#6]
ブラウザ間の見栄えを統一するためのCSS

https://webst8.com/blog/reset-css/

**Comment by sejsokdjfpsakd** [comment]
自分が使っているリセットCSS

https://github.com/elad2412/the-new-css-reset

**Comment by sejsokdjfpsakd** [comment]
CSS適用前
![スクリーンショット 2024-07-09 121441](https://github.com/MutsumeWebDev/training1/assets/172884135/4b12e22d-ce39-45fa-8d8a-7113829eb492)

**Comment by sejsokdjfpsakd** [comment]
CSS適用後
![スクリーンショット 2024-07-09 121508](https://github.com/MutsumeWebDev/training1/assets/172884135/cdea3f36-8aef-46e0-a4ab-8c4deea108da)

**Comment by oYAs-me** [comment]
確認しました

個人的には，上のようなhtmlだけでもある程度の構造が分かる方がなじみがあるので，リセットCSSはあっても最小限がいいのかなと思っています
リセットCSSを導入する，初心者レベルの開発に対するアドバンテージがあれば教えてもらえると嬉しいです．それがあるのに私が理解していないがためにアイデアを捨てるのはもったいないですしね

**Comment by sejsokdjfpsakd** [comment]
@oYAs-me さん
以前ご紹介したサイトなどにも書いてある通り、メリットは

・ブラウザ毎に異なるデフォルトCSSを打ち消し、ブラウザ間の表示の差異をなくすことができる
・意図しない余計なスタイルを打ち消すことでまっさらな状態から一からCSSの設定ができる

となります。(サイトから引用しましたが、他のサイトでもほとんど同じことが書かれているかと思います。)今回の趣旨に沿ったメリットは2つ目になると思いますが、それの裏返しのような感じでご指摘されたデメリットがあると思います。
私の考えとしては、

・`h1`,`h2`などといったタグは、CSSの書きやすさやサイトのSEO対策のためなどでしかないことを理解するため(デザインをCSSで出来るなら、わざわざタグを書き分けなくても`<p class="title">`,`<p class="sub-title">`などでも良いわけですし。)
・思い通りのデザインにするためのCSSトレーニングにもなること

から、リセットCSSを利用したほうが良いのではないか、と思います。(思考が初心者向けでなかったらすみません。)

**Comment by oYAs-me** [comment]
んー、初心者のレベルに立ってないような気がしているんですが、リセットcssを適用するタイミングはいつにするんですかね？
もし最初からであったとき、htmlを解説しているサイトと表示が異なって分かりづらいということがあるでしょう

**Comment by oYAs-me** [comment]
> `h1`,`h2`などといったタグは、CSSの書きやすさやサイトのSEO対策のためなどでしかないことを理解するため
ここに関しては一般論として，htmlは文章の構造をマークアップするものだから文章構造をCSSにゆだねてはならない，という基本概念を持っているしそれを広めたいので，この点に関しては全く賛同できません
2点目のCSSトレーニングになるという点については同意しますが，リセットCSSを導入した際のデメリットと比較してどうなるだろうかと判断しかねています．

**Comment by sejsokdjfpsakd** [comment]
@oYAs-me さん
> リセットcssを適用するタイミングはいつにするんですか

普通は一番最初からですね。(というか、そうでないと意味がないと思います。個人的な意見ですが。)

> htmlを解説しているサイトと表示が異なって分かりづらいということがある

確かに初心者向けサイトとビジュアルが違うのは混乱を招きかねないですね。

> htmlは文章の構造をマークアップするものだから文章構造をCSSにゆだねてはならない，という基本概念を持っているしそれを広めたい

SEO対策はHTMLの記述法のルール遵守という意味を含んでいます。私が主張したかったことは、デザインはタグによって決まるのではなくほとんどCSSによって決定されるものである、ということです。まわりくどい上に説明不足ですみません。
「文章構造をCSSにゆだねてはならない」というのは当然のこととして理解しているつもりです。(というか、あまり意識したことすらなかったですが。)

> リセットCSSを導入した際のデメリットと比較してどうなるだろうか
実際の運用ではメリットの方が大きく上回るとは思うのですが、今回は初心者向けトレーニングですからね･･･。

--------

ここまでで言えることは、少なくとも今回は初心者向けであることから、混乱を避けるために使用を控えた方が良さそう、といったところですかね。こんな感じの結論でどうでしょうか。

**Comment by oYAs-me** [comment]
そうですね〜〜

**Comment by oYAs-me** [comment]
wontfixでクローズしますね
